### ISSUE TITLE
Convert a generic Future into CompletableFuture

### ISSUE THREAD

**Issue by hamnis** [lukas-krecan/future-converter#5]
Could something like this be of interest? 

https://gist.github.com/hamnis/19b3eef14d0b79744fdc

**Comment by zinanxing** [comment]
I'd like to do a +1 on this question.

**Comment by lukas-krecan** [comment]
Sorry, I have completely forgotten about this issue. The trouble with converting future to something listenable as for example CompletableFuture is that you have to implement polling. There are various strategies to do it and it's impossible to pick a generic one. You can have one thread do all the polling, you can have thread pool, you can poll in constant interval, you can increase the polling time exponentially .... It's completely different task than just converting listenables between each other so it does not fit into this project.
